#include <Python.h>

PyDoc_STRVAR(doc__pcbdef,
"PCB definitions");

static struct PyModuleDef _pcbdef_module = {
    PyModuleDef_HEAD_INIT,
    "_pcbdef",
    doc__pcbdef,
    -1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC
PyInit__pcbdef(void) {
    PyObject *m = PyModule_Create(&_pcbdef_module);
    if (m == NULL) {
        return NULL;
    }

    PyModule_AddUnsignedLongConstant(m, "PCB_V_RES", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_DELPEN", 0x2UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_FORCPEN", 0x4UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_INQUAN", 0x8UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_PSWAPM", 0x10UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_RESPEN", 0x20UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_SSFEXC", 0x40UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_SSFEXCE", 0x80UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_SSFEXCS", 0x100UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_SSFEXCU", 0x200UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_SSRWAIT", 0x400UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_SUSPEN", 0x800UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_WALL", 0x2000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_BATCH", 0x4000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_NOACNT", 0x8000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_NOSUSPEND", 0x10000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_ASTPEN", 0x20000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_PHDRES", 0x40000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_HIBER", 0x80000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_LOGIN", 0x100000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_NETWRK", 0x200000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_PWRAST", 0x400000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_NODELET", 0x800000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_DISAWS", 0x1000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_INTER", 0x2000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_RECOVER", 0x4000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_HARDAFF", 0x10000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_ERDACT", 0x20000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_SOFTSUSP", 0x40000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_V_PREEMPTED", 0x80000000UL);

    PyModule_AddUnsignedLongConstant(m, "PCB_M_RES", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_DELPEN", 0x2UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_FORCPEN", 0x4UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_INQUAN", 0x8UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_PSWAPM", 0x10UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_RESPEN", 0x20UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SSFEXC", 0x40UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SSFEXCE", 0x80UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SSFEXCS", 0x100UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SSFEXCU", 0x200UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SSRWAIT", 0x400UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SUSPEN", 0x800UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_WALL", 0x2000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_BATCH", 0x4000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_NOACNT", 0x8000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_NOSUSPEND", 0x10000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_ASTPEN", 0x20000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_PHDRES", 0x40000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_HIBER", 0x80000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_LOGIN", 0x100000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_NETWRK", 0x200000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_PWRAST", 0x400000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_NODELET", 0x800000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_DISAWS", 0x1000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_INTER", 0x2000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_RECOVER", 0x4000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_HARDAFF", 0x10000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_ERDACT", 0x20000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SOFTSUSP", 0x40000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_PREEMPTED", 0x80000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_QUANTUM_RESCHED", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_DISABLE_PREEMPT_PKTA_LOCK", 0x2UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_FREDLOCK", 0x4UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_PHDLOCK", 0x8UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_TCB", 0x10UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_TBS_STATE_PENDING", 0x20UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SS_LOGGING_ENABLE", 0x40UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SS_LOGGING_PERM", 0x80UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_BRK_RUNDOWN_LOADED", 0x100UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_CLASS_SCHED_PERM", 0x8000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_TERM_NOTIFY", 0x10000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_BYTLM_LOAN", 0x20000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_DISABLE_PREEMPT", 0x40000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_NOUNSHELVE", 0x80000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SHELVING_RESERVED", 0x100000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_CLASS_SCHEDULED", 0x200000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_CLASS_SUPPLIED", 0x400000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_IN_TBS_STATE", 0x800000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_WINDFALL", 0x1000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_NOTIFY", 0x2000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SINGLE_THREADED", 0x3C000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_RWAST", 0x40000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SOFT_SINGLE_THREAD", 0x80000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_EPID_WILD", 0x80000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_FORK", 0x1UL);
    PyModule_AddIntConstant(m, "PCB_K_SCHED_OTHER", 0);
    PyModule_AddIntConstant(m, "PCB_K_SCHED_FIFO", 1);
    PyModule_AddIntConstant(m, "PCB_K_SCHED_RR", 2);
    PyModule_AddIntConstant(m, "PCB_K_SCHED_POLICY_CNT", 3);
    PyModule_AddIntConstant(m, "PCB_K_ALL_THREADS", -2147483648);
    PyModule_AddIntConstant(m, "PCB_K_MAX_KT_COUNT", 256);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_EVENT_NO_FLAG", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_IN_DELPAG", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_WAKEPEN", 0x1000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SECAUDIT", 0x8000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_UPCALL_AST_BLOCKED", 0x80000000UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SUGID_IMAGE", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "PCB_M_SUGID_PROCESS", 0x2UL);
    PyModule_AddIntConstant(m, "PCB_S_PCB", 2352);
    PyModule_AddIntConstant(m, "PCB_S_PHYPCB", 8);
    PyModule_AddIntConstant(m, "PCB_S_LEFC_SWAPPED", 8);
    PyModule_AddIntConstant(m, "PCB_S_PRVASN", 64);
    PyModule_AddIntConstant(m, "PCB_S_PRVASNSEQ", 8);
    PyModule_AddIntConstant(m, "PCB_S_ONCPUCNT", 8);
    PyModule_AddIntConstant(m, "PCB_S_SINGLE_THREADED", 4);
    PyModule_AddIntConstant(m, "PCB_S_EPID_PROC", 21);
    PyModule_AddIntConstant(m, "PCB_S_EPID_NODE_IDX", 8);
    PyModule_AddIntConstant(m, "PCB_S_EPID_NODE_SEQ", 2);
    PyModule_AddIntConstant(m, "PCB_S_PCBARB", 124);
    PyModule_AddIntConstant(m, "PCB_S_PRIV", 8);
    PyModule_AddIntConstant(m, "PCB_S_LNAME", 16);
    PyModule_AddIntConstant(m, "PCB_S_CWPSSRV_QUEUE", 8);
    PyModule_AddIntConstant(m, "PCB_S_BUFOBJ_LIST", 8);
    PyModule_AddIntConstant(m, "PCB_S_XSCB_QUE", 8);
    PyModule_AddIntConstant(m, "PCB_S_RMCB_QUE", 8);
    PyModule_AddIntConstant(m, "PCB_S_CD_QUE", 8);
    PyModule_AddIntConstant(m, "PCB_S_PSX_ACTPRM", 8);
    PyModule_AddIntConstant(m, "PCB_S_RDPB_QUE", 8);
    PyModule_AddIntConstant(m, "PCB_S_FILES_64", 8);
    PyModule_AddIntConstant(m, "PCB_S_KEEP_IN_WS", 8);
    PyModule_AddIntConstant(m, "PCB_S_KEEP_IN_WS2", 8);
    PyModule_AddIntConstant(m, "PCB_S_POSTEF", 8);
    PyModule_AddIntConstant(m, "PCB_S_ST_KT_ARRAY", 8);
    PyModule_AddIntConstant(m, "PCB_S_LOCKQFL", 8);
    PyModule_AddIntConstant(m, "PCB_S_LOCKQBL", 8);
    PyModule_AddIntConstant(m, "PCB_S_TQE_FLAGS", 8);
    PyModule_AddIntConstant(m, "PCB_S_CBB_PERM_CPU_AFFINITY", 48);
    PyModule_AddIntConstant(m, "PCB_S_PERMANENT_CPU_AFFINITY", 8);
    PyModule_AddIntConstant(m, "PCB_S_CBB_CURRENT_AFFINITY", 48);
    PyModule_AddIntConstant(m, "PCB_S_CURRENT_AFFINITY", 8);
    PyModule_AddIntConstant(m, "PCB_S_CBB_ACTIVE_CPUS", 48);
    PyModule_AddIntConstant(m, "PCB_S_ACTIVE_CPUS", 8);
    PyModule_AddIntConstant(m, "PCB_S_CBB_AFFINITIES", 48);
    PyModule_AddIntConstant(m, "PCB_S_AFFINITIES", 8);
    PyModule_AddIntConstant(m, "PCB_S_CBB_PERMANENT_AFFINITIES", 48);
    PyModule_AddIntConstant(m, "PCB_S_PERMANENT_AFFINITIES", 8);
    PyModule_AddIntConstant(m, "PCB_S_CBB_SAVED_AFFINITIES", 48);
    PyModule_AddIntConstant(m, "PCB_S_SAVED_AFFINITIES", 8);
    PyModule_AddIntConstant(m, "PCB_S_TERMINAL", 16);
    PyModule_AddIntConstant(m, "PCB_S_KERNEL_COUNTER_FRAC", 8);
    PyModule_AddIntConstant(m, "PCB_S_EXEC_COUNTER_FRAC", 8);
    PyModule_AddIntConstant(m, "PCB_S_SUPER_COUNTER_FRAC", 8);
    PyModule_AddIntConstant(m, "PCB_S_USER_COUNTER_FRAC", 8);
    PyModule_AddIntConstant(m, "PCB_K_LENGTH", 2352);
    PyModule_AddIntConstant(m, "PCB_C_LENGTH", 2352);
    PyModule_AddIntConstant(m, "PCB_S_PCBDEF", 2352);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_RES", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_DELPEN", 0x2UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_FORCPEN", 0x4UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_INQUAN", 0x8UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_PSWAPM", 0x10UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_RESPEN", 0x20UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SSFEXC", 0x40UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SSFEXCE", 0x80UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SSFEXCS", 0x100UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SSFEXCU", 0x200UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SSRWAIT", 0x400UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SUSPEN", 0x800UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_WALL", 0x2000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_BATCH", 0x4000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_NOACNT", 0x8000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_NOSUSPEND", 0x10000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_ASTPEN", 0x20000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_PHDRES", 0x40000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_HIBER", 0x80000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_LOGIN", 0x100000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_NETWRK", 0x200000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_PWRAST", 0x400000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_NODELET", 0x800000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_DISAWS", 0x1000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_INTER", 0x2000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_RECOVER", 0x4000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_HARDAFF", 0x10000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_ERDACT", 0x20000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SOFTSUSP", 0x40000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_PREEMPTED", 0x80000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_QUANTUM_RESCHED", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_PHDLOCK", 0x8UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_TCB", 0x10UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_TBS_STATE_PENDING", 0x20UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_CLASS_SCHED_PERM", 0x8000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_TERM_NOTIFY", 0x10000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_BYTLM_LOAN", 0x20000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_NOUNSHELVE", 0x80000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SHELVING_RESERVED", 0x100000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_CLASS_SCHEDULED", 0x200000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_CLASS_SUPPLIED", 0x400000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_IN_TBS_STATE", 0x800000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_WINDFALL", 0x1000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_NOTIFY", 0x2000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SINGLE_THREADED", 0x3C000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_EPID_WILD", 0x80000000UL);
    PyModule_AddIntConstant(m, "KTB_K_SCHED_OTHER", 0);
    PyModule_AddIntConstant(m, "KTB_K_SCHED_FIFO", 1);
    PyModule_AddIntConstant(m, "KTB_K_SCHED_RR", 2);
    PyModule_AddIntConstant(m, "KTB_K_SCHED_POLICY_CNT", 3);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_WAKEPEN", 0x1000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SECAUDIT", 0x8000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_UPCALL_AST_BLOCKED", 0x80000000UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_DELETE_PENDING", 0x1UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SCHED_CONTEXT_SAVED", 0x2UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SINGLE_THREAD_ACT", 0x3CUL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_TOLERANT", 0x40UL);
    PyModule_AddUnsignedLongConstant(m, "KTB_M_SOFT_RAD_AFFINITY", 0x80UL);
    PyModule_AddIntConstant(m, "KTB_S_KTB", 2352);
    PyModule_AddIntConstant(m, "KTB_S_PHYPCB", 8);
    PyModule_AddIntConstant(m, "KTB_S_SINGLE_THREADED", 4);
    PyModule_AddIntConstant(m, "KTB_S_EPID_PROC", 21);
    PyModule_AddIntConstant(m, "KTB_S_EPID_NODE_IDX", 8);
    PyModule_AddIntConstant(m, "KTB_S_EPID_NODE_SEQ", 2);
    PyModule_AddIntConstant(m, "KTB_S_SINGLE_THREAD_ACT", 4);
    PyModule_AddIntConstant(m, "KTB_S_CAPABILITIES", 8);
    PyModule_AddIntConstant(m, "KTB_S_PERMANENT_CAPABILITIES", 8);
    PyModule_AddIntConstant(m, "KTB_S_SAVED_CAPABILITIES", 8);
    PyModule_AddIntConstant(m, "KTB_S_VOL_WAITS", 8);
    PyModule_AddIntConstant(m, "KTB_S_COMQ_WAIT", 8);
    PyModule_AddIntConstant(m, "KTB_S_RUNTIME_START", 8);
    PyModule_AddIntConstant(m, "KTB_S_INTTIME_START", 8);
    PyModule_AddIntConstant(m, "KTB_S_ACC_RUN", 8);
    PyModule_AddIntConstant(m, "KTB_S_ACC_WAIT", 8);
    PyModule_AddIntConstant(m, "KTB_S_ACC_INTERRUPT", 8);
    PyModule_AddIntConstant(m, "KTB_S_GLOCK", 8);
    PyModule_AddIntConstant(m, "KTB_S_SCHED_COUNT", 8);
    PyModule_AddIntConstant(m, "KTB_S_FRED", 8);
    PyModule_AddIntConstant(m, "KTB_S_VIRPCB", 8);
    PyModule_AddIntConstant(m, "KTB_S_TQE_FLAGS", 8);
    PyModule_AddIntConstant(m, "KTB_S_CBB_PERM_CPU_AFFINITY", 48);
    PyModule_AddIntConstant(m, "KTB_S_PERMANENT_CPU_AFFINITY", 8);
    PyModule_AddIntConstant(m, "KTB_S_CBB_CURRENT_AFFINITY", 48);
    PyModule_AddIntConstant(m, "KTB_S_CURRENT_AFFINITY", 8);
    PyModule_AddIntConstant(m, "KTB_S_CBB_ACTIVE_CPUS", 48);
    PyModule_AddIntConstant(m, "KTB_S_ACTIVE_CPUS", 8);
    PyModule_AddIntConstant(m, "KTB_S_CBB_AFFINITIES", 48);
    PyModule_AddIntConstant(m, "KTB_S_AFFINITIES", 8);
    PyModule_AddIntConstant(m, "KTB_S_CBB_PERMANENT_AFFINITIES", 48);
    PyModule_AddIntConstant(m, "KTB_S_PERMANENT_AFFINITIES", 8);
    PyModule_AddIntConstant(m, "KTB_S_CBB_SAVED_AFFINITIES", 48);
    PyModule_AddIntConstant(m, "KTB_S_SAVED_AFFINITIES", 8);
    PyModule_AddIntConstant(m, "KTB_S_FP_DISABLED_ACTION", 8);
    PyModule_AddIntConstant(m, "KTB_S_KT_KERNEL_COUNTER_FRAC", 8);
    PyModule_AddIntConstant(m, "KTB_S_KT_EXEC_COUNTER_FRAC", 8);
    PyModule_AddIntConstant(m, "KTB_S_KT_SUPER_COUNTER_FRAC", 8);
    PyModule_AddIntConstant(m, "KTB_S_KT_USER_COUNTER_FRAC", 8);
    PyModule_AddIntConstant(m, "KTB_S_FP_LOW_SEQUENCE_NUMBER", 8);
    PyModule_AddIntConstant(m, "KTB_S_FP_HIGH_SEQUENCE_NUMBER", 8);
    PyModule_AddIntConstant(m, "KTB_S_POWER_ACCOUNTING", 8);
    PyModule_AddIntConstant(m, "KTB_S_DEF_SCHED_FKB", 48);
    PyModule_AddIntConstant(m, "KTB_K_LENGTH", 2352);
    PyModule_AddIntConstant(m, "KTB_C_LENGTH", 2352);
    PyModule_AddIntConstant(m, "KTB_S_KTBDEF", 2352);
    return m;
}